import { createHmac } from "node:crypto";
import type { QueryResultRow } from "pg";
import { canonicalJson, sha256Base64Url } from "../../infrastructure/crypto/canonical-json.js";
import type {
  AuditChainCheckpoint,
  PostgresAuditLedger,
} from "./postgres-audit-ledger.js";

const RETENTION_EVENT_TYPE = "mino.audit.checkpoint.retention.v1" as const;
const RETENTION_EVENT_ID_TYPE = "mino.audit.checkpoint.retention.event-id.v1";
const DEFAULT_BATCH_SIZE = 100;
const DEFAULT_TIMEOUT_MS = 5_000;
const MAX_STABLE_ISSUE_ATTEMPTS = 3;

export interface AuditCheckpointRetentionSqlClient {
  query<R extends QueryResultRow = QueryResultRow>(
    text: string,
    values?: unknown[],
  ): Promise<{ readonly rows: R[]; readonly rowCount: number | null }>;
}

export interface AuditCheckpointRetentionEvent {
  readonly eventId: string;
  readonly type: typeof RETENTION_EVENT_TYPE;
  readonly checkpoint: AuditChainCheckpoint;
}

export interface AuditCheckpointRetainer {
  retain(event: AuditCheckpointRetentionEvent): Promise<void>;
}

export interface WebhookAuditCheckpointRetainerOptions {
  readonly endpoint: string;
  readonly secret: string;
  readonly timeoutMs?: number;
}

export class WebhookAuditCheckpointRetainer implements AuditCheckpointRetainer {
  private readonly timeoutMs: number;

  public constructor(private readonly options: WebhookAuditCheckpointRetainerOptions) {
    const url = new URL(options.endpoint);
    if (url.protocol !== "https:") {
      throw new Error("Audit checkpoint retention endpoint must use HTTPS");
    }
    if (options.secret.length < 32) {
      throw new Error("Audit checkpoint retention secret must contain at least 32 characters");
    }
    this.timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
    if (!Number.isSafeInteger(this.timeoutMs) || this.timeoutMs <= 0) {
      throw new Error("Audit checkpoint retention timeout must be a positive integer");
    }
  }

  public async retain(event: AuditCheckpointRetentionEvent): Promise<void> {
    const body = canonicalJson(event);
    const timestamp = Math.floor(Date.now() / 1000).toString(10);
    const signature = createHmac("sha256", this.options.secret)
      .update(`${timestamp}.${body}`)
      .digest("hex");

    const response = await fetch(this.options.endpoint, {
      method: "POST",
      redirect: "error",
      headers: {
        "Content-Type": "application/json",
        "X-Mino-Event-Id": event.eventId,
        "X-Mino-Audit-Organization-Id": event.checkpoint.organizationId,
        "X-Mino-Audit-Sequence": event.checkpoint.chainSequence,
        "X-Mino-Signature": `t=${timestamp},v1=${signature}`,
      },
      body,
      signal: AbortSignal.timeout(this.timeoutMs),
    });

    if (!response.ok) {
      throw new Error(`Audit checkpoint retention endpoint rejected event with HTTP ${response.status}`);
    }
  }
}

export interface AuditCheckpointRetentionWorkerOptions {
  readonly batchSize?: number;
}

export interface AuditCheckpointRetentionRunResult {
  readonly considered: number;
  readonly delivered: number;
  readonly alreadyDelivered: number;
  readonly failed: number;
}

interface AuditHeadRow extends QueryResultRow {
  organizationId: string;
  chainSequence: string;
  chainDigest: string;
  updatedAt: Date;
}

interface AuditCheckpointIssuer {
  issueCheckpoint(organizationId: string, now: Date): Promise<AuditChainCheckpoint>;
}

/**
 * Periodically exports signed audit-chain checkpoints to a separate retention service.
 *
 * Delivery is deliberately at-least-once. Successful event IDs are remembered only in
 * process memory to suppress needless repeats while a process stays alive. A restart or
 * another Mino instance may resend the same stable event; the external retention service
 * must deduplicate X-Mino-Event-Id and durably retain the signed checkpoint before 2xx.
 *
 * The checkpoint itself is generated by PostgresAuditLedger. We pass the chain head's
 * updatedAt timestamp as issuedAt and verify that the head did not advance during signing,
 * which makes the checkpoint payload and event ID stable for an unchanged chain head.
 */
export class AuditCheckpointRetentionWorker {
  private readonly batchSize: number;
  private cursorOrganizationId: string | undefined;
  private readonly deliveredEventByOrganization = new Map<string, string>();

  public constructor(
    private readonly sql: AuditCheckpointRetentionSqlClient,
    private readonly ledger: Pick<PostgresAuditLedger, "issueCheckpoint"> | AuditCheckpointIssuer,
    private readonly retainer: AuditCheckpointRetainer,
    options: AuditCheckpointRetentionWorkerOptions = {},
  ) {
    this.batchSize = options.batchSize ?? DEFAULT_BATCH_SIZE;
    if (!Number.isSafeInteger(this.batchSize) || this.batchSize <= 0) {
      throw new Error("Audit checkpoint retention batch size must be a positive integer");
    }
  }

  public async runOnce(): Promise<AuditCheckpointRetentionRunResult> {
    let heads = await this.loadHeads(this.cursorOrganizationId);
    if (heads.length === 0 && this.cursorOrganizationId) {
      this.cursorOrganizationId = undefined;
      heads = await this.loadHeads(undefined);
    }

    if (heads.length === this.batchSize) {
      this.cursorOrganizationId = heads[heads.length - 1]?.organizationId;
    } else {
      this.cursorOrganizationId = undefined;
    }

    let delivered = 0;
    let alreadyDelivered = 0;
    let failed = 0;

    for (const head of heads) {
      try {
        const checkpoint = await this.issueStableCheckpoint(head.organizationId);
        const event = retentionEvent(checkpoint);
        if (this.deliveredEventByOrganization.get(head.organizationId) === event.eventId) {
          alreadyDelivered += 1;
          continue;
        }

        await this.retainer.retain(event);
        this.deliveredEventByOrganization.set(head.organizationId, event.eventId);
        delivered += 1;
      } catch {
        failed += 1;
      }
    }

    return {
      considered: heads.length,
      delivered,
      alreadyDelivered,
      failed,
    };
  }

  private async loadHeads(afterOrganizationId: string | undefined): Promise<AuditHeadRow[]> {
    const result = await this.sql.query<AuditHeadRow>(
      `select h."organizationId",
              h."chainSequence"::text as "chainSequence",
              h."chainDigest",
              h."updatedAt"
         from "AuditChainHead" h
        where h."chainSequence" > 0
          and h."chainDigest" is not null
          and ($1::uuid is null or h."organizationId" > $1::uuid)
        order by h."organizationId" asc
        limit $2`,
      [afterOrganizationId ?? null, this.batchSize],
    );
    return result.rows;
  }

  private async issueStableCheckpoint(organizationId: string): Promise<AuditChainCheckpoint> {
    for (let attempt = 0; attempt < MAX_STABLE_ISSUE_ATTEMPTS; attempt += 1) {
      const before = await this.loadHead(organizationId);
      if (!before) {
        throw new Error("Audit chain head disappeared before checkpoint issuance");
      }
      const checkpoint = await this.ledger.issueCheckpoint(organizationId, before.updatedAt);
      if (
        checkpoint.chainSequence === before.chainSequence &&
        checkpoint.chainDigest === before.chainDigest
      ) {
        return checkpoint;
      }
    }
    throw new Error("Audit chain advanced repeatedly while issuing retention checkpoint");
  }

  private async loadHead(organizationId: string): Promise<AuditHeadRow | undefined> {
    const result = await this.sql.query<AuditHeadRow>(
      `select h."organizationId",
              h."chainSequence"::text as "chainSequence",
              h."chainDigest",
              h."updatedAt"
         from "AuditChainHead" h
        where h."organizationId" = $1::uuid
          and h."chainSequence" > 0
          and h."chainDigest" is not null`,
      [organizationId],
    );
    return result.rows[0];
  }
}

export function retentionEvent(checkpoint: AuditChainCheckpoint): AuditCheckpointRetentionEvent {
  const eventId = sha256Base64Url(
    canonicalJson({
      type: RETENTION_EVENT_ID_TYPE,
      version: checkpoint.version,
      organizationId: checkpoint.organizationId,
      chainSequence: checkpoint.chainSequence,
      chainDigest: checkpoint.chainDigest,
      issuedAt: checkpoint.issuedAt,
      signingKeyId: checkpoint.signingKeyId,
      signature: checkpoint.signature,
    }),
  );
  return {
    eventId,
    type: RETENTION_EVENT_TYPE,
    checkpoint,
  };
}
